import {test} from 'node:test';
import assert from 'node:assert/strict';
import {DatabaseSync} from 'node:sqlite';
import {readFileSync} from 'node:fs';
import {Store,validMutation} from '../lib/store.ts';
const schema=readFileSync(new URL('../drizzle/0000_futuristic_forge.sql',import.meta.url),'utf8');
const catalogue=JSON.parse(readFileSync(new URL('../lib/catalogue.json',import.meta.url),'utf8'));
class DB {
 constructor(){this.conn=new DatabaseSync(':memory:');this.conn.exec('PRAGMA foreign_keys=ON');this.conn.exec(schema)}
 prepare(sql){const db=this;return new class {args=[];bind(...args){this.args=args;return this}exec(){const r=db.conn.prepare(sql).run(...this.args);return {meta:{changes:Number(r.changes),last_row_id:Number(r.lastInsertRowid)}}}async run(){return this.exec()}async all(){return {results:db.conn.prepare(sql).all(...this.args)}}}}
 async batch(statements){this.conn.exec('BEGIN');try{const result=statements.map(s=>s.exec());this.conn.exec('COMMIT');return result}catch(e){this.conn.exec('ROLLBACK');throw e}}
}
async function setup(){const db=new DB(),a=new Store(db,'alice'),b=new Store(db,'bob'),guest=new Store(db,null);await a.seed(catalogue);await a.ensureUser();await b.ensureUser();return {db,a,b,guest}}
const read=(s,view,extra={})=>s.read(new URLSearchParams({view,...Object.fromEntries(Object.entries(extra).map(([k,v])=>[k,String(v)]))}));
const rejects=(p,status)=>assert.rejects(p,e=>e.status===status);
const list=async a=>(await a.mutate({action:'list_create',name:'Reading',description:'notes'})).id;
test('literal search, author filter, stable pagination and seed idempotence',async()=>{const {a}=await setup();assert.equal((await read(a,'papers')).total,16);assert.equal((await read(a,'papers',{q:'%',page:1})).total,0);assert.equal((await read(a,'papers',{q:'Tiny',author:'Researcher A',year:2025})).total,1);const p1=await read(a,'papers'),p2=await read(a,'papers',{page:2});assert.equal(new Set([...p1.rows,...p2.rows].map(p=>p.paper_id)).size,16);await a.seed(catalogue);assert.equal((await read(a,'papers')).total,16);await rejects(read(a,'papers',{year:'bad'}),400)});
test('private list isolation covers reads and every mutation',async()=>{const {a,b,guest}=await setup();const id=await list(a);await rejects(read(b,'list',{id}),404);await rejects(read(guest,'lists'),401);for(const action of ['list_edit','list_delete','list_visibility','list_add','list_remove'])await rejects(b.mutate({action,id,version:1,public:true,paper_ids:[1],paper_id:1,name:'stolen'}),404);assert.equal((await read(a,'lists')).total,1)});
test('atomic batch rejects invalid papers; duplicate membership stays unique',async()=>{const {a}=await setup();const id=await list(a);await rejects(a.mutate({action:'list_add',id,version:1,paper_ids:[1,999999]}),400);assert.equal((await read(a,'list',{id})).total,0);await a.mutate({action:'list_add',id,version:1,paper_ids:[1,2,2]});assert.equal((await read(a,'list',{id})).total,2);await rejects(a.mutate({action:'list_add',id,version:1,paper_ids:[3]}),409);assert.equal((await read(a,'list',{id})).total,2)});
test('concurrent list CAS has one winner and no partial loser additions',async()=>{const {a}=await setup();const id=await list(a);const results=await Promise.allSettled([a.mutate({action:'list_add',id,version:1,paper_ids:[1]}),a.mutate({action:'list_add',id,version:1,paper_ids:[2]})]);assert.equal(results.filter(r=>r.status==='fulfilled').length,1);assert.equal((await read(a,'list',{id})).total,1)});
test('progress survives membership deletion and rejects stale writes',async()=>{const {a,b}=await setup();const id=await list(a);await a.mutate({action:'progress',paper_id:1,version:0,status:'reading'});await rejects(a.mutate({action:'progress',paper_id:1,version:0,status:'read'}),409);await a.mutate({action:'list_add',id,version:1,paper_ids:[1]});await a.mutate({action:'list_remove',id,version:2,paper_id:1});assert.equal((await read(a,'progress')).total,1);assert.equal((await read(b,'progress')).total,0);await a.mutate({action:'progress',paper_id:1,version:1,status:'read'});await rejects(a.mutate({action:'progress',paper_id:1,version:1,status:'want'}),409)});
test('public sharing revokes links and never exposes private progress or identity IDs',async()=>{const {a,b,guest}=await setup();const id=await list(a);await a.mutate({action:'list_add',id,version:1,paper_ids:[1]});await a.mutate({action:'progress',paper_id:1,version:0,status:'reading'});await rejects(read(guest,'shared',{id}),404);await a.mutate({action:'list_visibility',id,version:2,public:true});const shared=await read(guest,'shared',{id});assert.equal(shared.rows[0].status,undefined);assert.equal(shared.item.owner_id,undefined);assert.equal(shared.item.user_id,undefined);assert.equal((await read(guest,'community')).total,1);await b.mutate({action:'vote',kind:'list',id,like:true});assert.equal((await read(guest,'shared',{id})).item.votes,1);await a.mutate({action:'list_visibility',id,version:3,public:false});await rejects(read(b,'shared',{id}),404);await rejects(b.mutate({action:'vote',kind:'list',id,like:true}),404)});
test('reviews are unique, editable, owned, escaped as data and averaged correctly',async()=>{const {a,b,guest}=await setup();await a.mutate({action:'review_save',paper_id:1,version:0,rating:5,body:'<script>test</script>'});await rejects(a.mutate({action:'review_save',paper_id:1,version:0,rating:2,body:'duplicate'}),409);await b.mutate({action:'review_save',paper_id:1,version:0,rating:3,body:'B'});const paper=await read(guest,'paper',{id:1});assert.equal(paper.rating.average_rating,4);assert.equal(paper.rows[1].body,'<script>test</script>');assert.equal(paper.rows[1].user_id,undefined);await rejects(b.mutate({action:'review_delete',id:paper.rows[1].review_id,version:1}),404);await a.mutate({action:'review_save',paper_id:1,version:1,rating:1,body:'updated'});assert.equal((await read(guest,'paper',{id:1})).rating.average_rating,2)});
test('review votes are idempotent, concurrent-safe, cannot self-vote, and cascade',async()=>{const {a,b}=await setup();await a.mutate({action:'review_save',paper_id:1,version:0,rating:5,body:'A'});const id=(await read(a,'paper',{id:1})).rows[0].review_id;await rejects(a.mutate({action:'vote',kind:'review',id,like:true}),400);await Promise.all([b.mutate({action:'vote',kind:'review',id,like:true}),b.mutate({action:'vote',kind:'review',id,like:true})]);assert.equal((await read(a,'paper',{id:1})).rows[0].votes,1);await b.mutate({action:'vote',kind:'review',id,like:false});await b.mutate({action:'vote',kind:'review',id,like:false});assert.equal((await read(a,'paper',{id:1})).rows[0].votes,0);await b.mutate({action:'vote',kind:'review',id,like:true});await a.mutate({action:'review_delete',id,version:1});assert.equal((await a.one('SELECT COUNT(*) n FROM review_votes')).n,0)});
test('rankings apply minimum/year filters and stable averages, not helpful votes',async()=>{const {a,b,guest}=await setup();assert.equal((await read(guest,'leaderboard')).total,0);for(const [s,pid,rating] of [[a,1,5],[b,1,3],[a,2,5]])await s.mutate({action:'review_save',paper_id:pid,version:0,rating,body:'review'});assert.deepEqual((await read(guest,'leaderboard')).rows.map(p=>p.paper_id),[1]);assert.deepEqual((await read(guest,'leaderboard',{minimum:1})).rows.map(p=>p.paper_id),[2,1]);assert.deepEqual((await read(guest,'leaderboard',{minimum:1,year:2025})).rows.map(p=>p.paper_id),[1])});
test('posts and one-level replies support ownership, versions, votes and cascading deletion',async()=>{const {a,b,guest}=await setup();const id=(await a.mutate({action:'post_create',paper_id:1,title:'Question',body:'A'})).id;await b.mutate({action:'reply_create',post_id:id,body:'Reply'});await b.mutate({action:'vote',kind:'post',id,like:true});let post=await read(b,'post',{id});assert.equal(post.item.votes,1);assert.equal(post.rows[0].mine,true);const rid=post.rows[0].reply_id;await rejects(a.mutate({action:'reply_edit',id:rid,version:1,body:'stolen'}),404);await b.mutate({action:'reply_edit',id:rid,version:1,body:'edited'});await a.mutate({action:'post_edit',id,version:1,title:'Updated',body:'changed'});await rejects(a.mutate({action:'post_delete',id,version:1}),409);await a.mutate({action:'post_delete',id,version:2});await rejects(read(guest,'post',{id}),404);assert.equal((await a.one('SELECT COUNT(*) n FROM replies')).n,0);assert.equal((await a.one('SELECT COUNT(*) n FROM post_votes')).n,0)});
test('author graph counts distinct direct collaboration only',async()=>{const {guest}=await setup();const n=await read(guest,'network',{id:1});assert.deepEqual(n.neighbors.map(a=>[a.author_id,a.shared_papers]),[[2,2],[8,2]]);await rejects(read(guest,'network',{id:9999}),404)});
test('deleting a list retains papers and progress but removes memberships and likes',async()=>{const {a,b}=await setup();const id=await list(a);await a.mutate({action:'list_edit',id,version:1,name:'Renamed',description:'Changed'});await a.mutate({action:'list_add',id,version:2,paper_ids:[1]});await a.mutate({action:'list_visibility',id,version:3,public:true});await b.mutate({action:'vote',kind:'list',id,like:true});await a.mutate({action:'list_delete',id,version:4});assert.equal((await a.one('SELECT COUNT(*) n FROM list_votes')).n,0);assert.equal((await a.one('SELECT COUNT(*) n FROM papers')).n,16)});
test('forged actions and malformed inputs do not mutate other data',async()=>{const {a,guest}=await setup();await rejects(guest.mutate({action:'profile',name:'x'}),401);await rejects(a.mutate({action:'vote',kind:'users; DROP TABLE papers',id:1,like:true}),400);await rejects(a.mutate({action:'profile',name:' '}),400);await rejects(a.mutate({action:'review_save',paper_id:1,version:0,rating:9,body:'x'}),400);await rejects(a.mutate({action:'post_create',paper_id:1,title:'x',body:''}),400);await a.mutate({action:'profile',name:'A learner'});assert.equal((await a.ensureUser()).display_name,'A learner')});
test('mutation boundary rejects cross-site, missing origin, and form-encoded requests',()=>{const req=(origin,type='application/json',header='1')=>new Request('https://navigator.example/api/data',{method:'POST',headers:{...(origin?{Origin:origin}:{}),'Content-Type':type,'X-Navigator-Action':header}});assert.equal(validMutation(req('https://navigator.example')),true);assert.equal(validMutation(req('https://evil.example')),false);assert.equal(validMutation(req(null)),false);assert.equal(validMutation(req('https://navigator.example','application/x-www-form-urlencoded')),false);assert.equal(validMutation(req('https://navigator.example','application/json','')),false)});
